annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 2.16.2
name: fe-administrator
description: A Helm chart for Administrator Web for CZERTAINLY platform.
home: https://github.com/CZERTAINLY/CZERTAINLY-FE-Administrator
icon: https://github.com/CZERTAINLY/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
dependencies:
  - name: czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../czertainly-lib
    version: 1.4.2
keywords:
  - czertainly
  - trust
  - management
  - lifecycle
  - platform
  - fe
  - administrator
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/CZERTAINLY/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/CZERTAINLY/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
version: 2.16.2
