annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.6.0
name: ms-adcs-connector
description: A Helm chart for MS ADCS Connector for CZERTAINLY platform.
home: https://github.com/3KeyCompany/CZERTAINLY-MS-ADCS-Connector
icon: https://github.com/3KeyCompany/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
dependencies:
  - name: czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../czertainly-lib
    version: 1.3.0
keywords:
  - czertainly
  - trust
  - management
  - lifecycle
  - platform
  - ms
  - adcs
  - authority
  - discovery
  - provider
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/3KeyCompany/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/3KeyCompany/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
version: 1.6.0-1
