apiVersion: v1
data:
  # if the global values are defined, use it, otherwise use local values
  database_host: {{ pluck "host" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  database_port: {{ pluck "port" .Values.global.database .Values.database | compact | first | toString | b64enc | quote }}
  database_name: {{ pluck "name" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  database_user: {{ pluck "username" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  database_password: {{ pluck "password" .Values.global.database .Values.database | compact | first | b64enc | quote }}
kind: Secret
metadata:
  name: pyadcs-connector-secret
