annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 3.9.1
name: api-gateway-kong
description: A Helm chart for API Gateway based on the Kong for CZERTAINLY platform.
home: https://github.com/CZERTAINLY/CZERTAINLY
icon: https://github.com/CZERTAINLY/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
dependencies:
  - name: czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../czertainly-lib
    version: 1.4.2
keywords:
  - czertainly
  - trust
  - management
  - lifecycle
  - platform
  - api
  - gateway
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/CZERTAINLY/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/CZERTAINLY/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
  - https://github.com/revomatico/docker-kong-oidc
  - https://github.com/revomatico/kong-oidc
version: 3.9.1-develop
