annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.3.0
name: auth-service
description: A Helm chart for CZERTAINLY Auth service.
home: https://github.com/3KeyCompany/CZERTAINLY-Auth
icon: https://github.com/3KeyCompany/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
dependencies:
  - name: czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../czertainly-lib
    version: 1.3.0
keywords:
  - czertainly
  - trust
  - management
  - lifecycle
  - platform
  - auth
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/3KeyCompany/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/3KeyCompany/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
version: 1.3.0-1
