apiVersion: v1
data:
  # if the global values are defined, use it, otherwise use local values
  dbPassword: {{ pluck "password" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  dbUsername: {{ pluck "username" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  smtpPassword: {{ .Values.smtp.password | b64enc | quote }}
  smtpUsername: {{ .Values.smtp.username | b64enc | quote }}
kind: Secret
metadata:
  name: email-notification-provider-secret